config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: :index
end

app/models/badge.rb
class Badge < ApplicationRecord
  #RULES = %w[category level first_attempt].freeze

  has_many :received_awards, dependent: :destroy
  has_many :users, through: :received_awards

  validates :name, :picture, presence: true
  validates :rule, inclusion: { in: BadgeService::RULES }, uniqueness: { scope: :parameter }

end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  def index
    @badges = Badge.all
    @issued_badges = current_user.badges
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :picture, :rule, :parameter)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    @issued_badges = current_user.badges
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def rules
    BadgeService::RULES.map { |rule| [t("badge_rules.#{rule}"), rule] }
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.name %></td>
  <td><%= badge.picture %></td>
  <td><%= badge.rule %></td>
  <td><%= badge.parameter %></td>
  <td>
    <%= link_to 'Edit', edit_admin_badge_path(badge)%>
  </td>
  <td>
    <%= link_to 'Delete',
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/error', resource: @badge %>

  <p>
    <%= form.label :name, "Name" %><br>
    <%= form.text_field :name, id: :badge_name %>
  </p>

  <p>
    <%= form.label :picture, "Picture" %><br>
    <%= form.text_field :picture, id: :badge_picture %>
  </p>

  <p>
    <%= form.label :rule, t('badge_rules.rule')  %><br>
    <%= form.select :rule, rules  %>
  </p>

  <p>
    <%= form.label :parameter, "Parameter" %><br>
    <%= form.text_field :parameter, id: :badge_parameter %>
  </p>

  <p><%= form.submit %></p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Editing Badge</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Rule</th>
      <th>Parameter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @badges %>
  </tbody>
</table>

<%= link_to 'New Badge', new_admin_badge_path %>
<%= link_to 'Back', admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form'%>

<%= link_to 'Back', admin_badges_path %>