config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: :index
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :option, presence: true
  validate :limiting_responses, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def limiting_responses
    errors.add(:option) if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  #RULES = %w[category level first_attempt].freeze

  has_many :received_awards, dependent: :destroy
  has_many :users, through: :received_awards

  validates :name, :picture, presence: true
  validates :rule, inclusion: { in: BadgeService::RULES }, uniqueness: { scope: :parameter }

end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :nullify

  validates :title, presence: true
end

app/models/examination.rb
class Examination < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :url, presence: true

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :description, presence: true
end

app/models/received_award.rb
class ReceivedAward < ApplicationRecord
  belongs_to :badge
  belongs_to :user
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :author, class_name: 'User', foreign_key: :author_id, optional: true
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  validates :title, presence: true,
                    uniqueness: { scope: :level }
  validates :level, :timer, numericality: { only_integer: true,
                                    greater_than_or_equal_to: 1 }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :sort_by_category, -> (category) { joins(:category)
                                            .where(categories: { title: category })
                                            .order(title: :desc) }

  def self.sort_by_category_return_array(category)
    sort_by_category(category).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end

  def time_left
    (created_at + test.timer * 60 - Time.current).to_i
  end

  def time_is_up?
    time_left <= 0
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
      self.passed = succesfully?
      self.current_question = nil if time_is_up?
    end

    save!
  end

  def success_rate
    (100 * correct_questions.to_f / test.questions.count).round
  end

  def succesfully?
    success_rate >= 85
  end

   def number_current_question
     test.questions.count - other_questions.count
   end

  private

  def set_current_question
    self.current_question = next_question
  end

  def other_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def next_question
    if current_question
      other_questions.first
    else
      test.questions.first
    end
  end

  def correct_answer?(answer_ids)
    #correct_answers.ids.sort == answer_ids.map(&:to_i).sort этим методом нельзя передавать пустые ответы
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages do
    def success
      where("test_passages.passed = ?", true)
    end

    def after_badge_issue(time_of_issue)
      where("test_passages.updated_at > ?", time_of_issue)
    end
  end
  has_many :created_tests, class_name: 'Test', foreign_key: :author_id
  has_many :gists, dependent: :destroy
  has_many :received_awards, dependent: :destroy
  has_many :badges, through: :received_awards

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  def list_tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    @issued_badges = current_user.badges
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[update edit show destroy start]

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def flash_message(type)
    content_tag :p, flash[type.to_sym], class: "flash flash #{type}"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def rules
    BadgeService::RULES.map { |rule| [t("badge_rules.#{rule}"), rule] }
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<div class="nav nav-admin">
  <span class="nav-admin title">TestGuru Admin Panel </span>

  <div class="nav-admin user">
    Welcome, <b class="nav-admin user-email"><%= current_user.email %></b> Guru |
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
  </div>
</div>
<p class='big_letters'><%= link_to 'View gists', admin_gists_path %></p>
<p class='big_letters'><%= link_to 'Badges', admin_badges_path %></p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'admin/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= render 'shared/flash' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if resource.present? && resource.errors.any? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <div>
      <h2><%= pluralize(resource.errors.count, 'error') %> detected:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, class: "flash #{key}" %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
<p>
  <%= current_year %> Alaev Musost <br>
  <%= link_to 'TestGuru', github_url('prostojchelovek', 'Rails')%> - Приложение для прохождения тестов<br>
  <%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'http://thinknetica.com' %>
</p>
</footer>

app/views/shared/_nav.html.erb
<nav>
  <h1><%= link_to 'TestGuru', root_path %></h1>
  <h1><%= link_to 'Badges', badges_path %></h1>

  <% if user_signed_in? %>
    <p class='nav nav user'>
      Welcome, <%= "#{current_user.first_name} #{current_user.last_name}"%><br>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    </p>
  <% end %>
</nav>