config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :description, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :set_current_question

  def completed?
    current_question.nil?
  end

  def time_left
    (created_at + test.timer * 60 - Time.current).to_i
  end

  def time_is_up?
    time_left <= 0
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
      self.passed = succesfully?
      self.current_question = nil if time_is_up?
    end

    save!
  end

  def success_rate
    (100 * correct_questions.to_f / test.questions.count).round
  end

  def succesfully?
    success_rate >= 85
  end

   def number_current_question
     test.questions.count - other_questions.count
   end

  private

  def set_current_question
    self.current_question = next_question
  end

  def other_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

  def next_question
    if current_question
      other_questions.first
    else
      test.questions.first
    end
  end

  def correct_answer?(answer_ids)
    #correct_answers.ids.sort == answer_ids.map(&:to_i).sort этим методом нельзя передавать пустые ответы
    correct_answers_count = correct_answers.count

    (correct_answers_count == correct_answers.where(id: answer_ids).count) &&
    correct_answers_count == answer_ids.count
  end

  def correct_answers
    current_question.answers.correct
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show result update gist]

  def show
  end

  def result
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      current_user.badges << BadgeService.new(@test_passage).check_badges
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    service = GistQuestionService.new(@test_passage.current_question)
    url = service.call.html_url

    if service.success?
      current_user.gists.create(question: @test_passage.current_question, url: url)
      flash_options = { notice: t('.success', link: view_context.link_to('Link', url)) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<% if @test_passage.succesfully? %>
  <h1 class='succes'>Test passed successfully</h1>
<% else %>
  <h1 class='fail'>Test failed</h1>
<% end %>
<div class='progress'>
  <div class="bar" data-percentage=<%= @test_passage.success_rate %> ></div>
</div>

app/views/test_passages/show.html.erb
<h1>Passing the <%= @test_passage.test.title %> Test</h1>

<p>
  Current question <%= @test_passage.number_current_question %><br>
</p>

<b>
  <%= @test_passage.current_question.description %>
</b>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put, data: { time_left: @test_passage.time_left }, class: "test-passage" do |form| %>
  <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :option, include_hidden:
  false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>

<p><%= form.submit 'Next' %> </p>
<p class="timer big_letters"> </p>
<p><%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post %></p>
<% end %>