config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    resources :questions, shallow: true, except: :index do
      resources :answers, shallow: true, except: :index
    end

    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

  resources :badges, only: :index
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :test_passages, foreign_key: :current_question_id, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :description, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[edit update show destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show
  end

  def new
    @question = @test.questions.new
  end

  def edit
  end

  def destroy
    @question.destroy!
    redirect_to admin_test_path(@question.test)
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:description)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_test, only: %i[new create]
  before_action :find_question, only: %i[edit update show destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found
=begin
  def show
  end

  def new
    @question = @test.questions.new
  end

  def edit
  end

  def destroy
    @question.destroy!
    redirect_to @question.test
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to @question.test
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question.test
    else
      render :edit
    end
  end

  private

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:description)
  end

  def rescue_with_question_not_found
    render plain: 'Вопрос не найден'
  end
=end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with model: [:admin, @test, @question], local: true do |form| %>
  <%= render 'shared/error', resource: @question %>

  <%= form.label :description %>
  <%= form.text_field :description, id: :question_description %>
  <%= form.submit %>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.description %></td>
  <td><%= link_to 'Show', admin_question_path(question) %> </td>
  <td><%= link_to 'Edit', edit_admin_question_path(question) %> </td>
  <td>
    <%= link_to 'Delete',
                admin_question_path(question),
                method: :delete,
                data: { confirm: 'Are you sure?' }
    %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<p><%= question_header(@question) %></p>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test.id) %>

app/views/admin/questions/new.html.erb
<p><%= question_header(@question) %></p>

<%= render 'form' %>

<%= link_to 'Back', admin_test_path(@question.test.id) %>

app/views/admin/questions/show.html.erb
<h1><%= @question.test.title %> Question</h1>

<p>
  <%= @question.description %>
</p>

<h2>Answers</h2>

<%= link_to 'New Answer', new_admin_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>

<%= link_to 'Edit', edit_admin_question_path(@question) %>
<%= link_to 'Back', admin_test_path(@question.test) %>